#!/bin/bash
gcc -E $CFILE -0 c
[Aoi[3~[3~[3~[3~[3~[3~[3~[3~[3~[3~[3~[3~[3~[3~[3~[3~[3~[3~[3[3~[3~[3~
gcc -E $CFILE -o c
[A
gcc -E $CFILE -0 C
ls
q
e
:wq
clear
exit
cd ..
[3~

